import 'babel-polyfill';
import './es6/class1'
import './es6/class2'
// import './es6/class3'
// import './es6/class4'
// import './es6/class5'
// import './es6/class6'
// import './es6/class7'
// import './es6/class8'
// import './es6/class9'
// import './es6/class10'
// import './es6/class11'
// import './es6/class12'
// import './es6/class13'
// import './es6/class14'
// import './es6/class15'
// import './es6/class16'
// import './es6/class17'